portfolio/contact/urls.py
from . import views
from django.urls import path
app_name = 'contact'
urlpatterns = [
    path('contact/', views.contact, name='contact'),
]

portfolio/edu/urls.py
from . import views
from django.urls import path
app_name = 'edu'
urlpatterns = [
    path('', views.edu, name='edu'),
]

portfolio/experience/urls.py
from . import views
from django.urls import path
app_name = 'experience'
urlpatterns = [
    path('', views.experience, name='experience'),
]

portfolio/home/urls.py
from . import views
from django.urls import path
app_name = 'home'
urlpatterns = [
    path('', views.home, name = 'home'), 
]

portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contactview/', include(('contact.urls', 'contact'), namespace='contact')),
    path('educationview/', include(('edu.urls', 'edu'), namespace='edu')),
    path('experiencesview/', include(('experience.urls', 'experience'), namespace='experience')),
    path('projectview/', include(('project.urls', 'project'), namespace='project')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('skillview/', include(('skill.urls', 'skill'), namespace='skill')),
    path('serviceview/', include(('service.urls', 'service'), namespace='service')),
]

portfolio/project/urls.py
from . import views
from django.urls import path

app_name = 'project'

urlpatterns = [
    path('', views.project, name='project'),
]

portfolio/service/urls.py
from . import views
from django.urls import path
app_name = 'service'
urlpatterns = [
    path('', views.service, name='service'),
]

portfolio/skill/urls.py
from . import views
from django.urls import path
app_name = 'skill'
urlpatterns = [
    path('', views.skill, name='skill'),
]

portfolio/contact/models.py
from django.db import models

# Create your models here.

portfolio/edu/models.py
from django.db import models

# Create your models here.

portfolio/experience/models.py
from django.db import models

# Create your models here.

portfolio/home/models.py
from django.db import models

# Create your models here.

portfolio/project/models.py
from django.db import models

# Create your models here.

portfolio/service/models.py
from django.db import models

# Create your models here.

portfolio/skill/models.py
from django.db import models

# Create your models here.

portfolio/contact/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def contact(request):
    return render(request, 'contact/contact.html')

portfolio/edu/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def edu(request):
    return render(request, 'edu/edu.html')

portfolio/experience/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def experience(request):
    return render(request, 'experience/exp.html')

portfolio/home/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home/home.html')

portfolio/project/views.py
from django.http import HttpResponse
from django.shortcuts import render

def project(request):
    return render(request, 'project/project.html')

portfolio/service/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def service(request):
    return render(request, 'service/service.html')

portfolio/skill/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def skill(request):
    return render(request, 'skill/skill.html')

portfolio/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Profile
      {% endblock %}
    </title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    {% block extra_css %}{% endblock %}
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="logo">
          <a href="{% url 'home:home' %}" class="logo-link"><img src="{% static 'images/R.png' %}" alt="Logo" class="logo-image" /></a>
        </div>
        <nav class="main-nav">
          <ul class="nav-links">
            <li>
              <a href="{% url 'home:home' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">Home</a>
            </li>
            <li>
              <a href="{% url 'project:project' %}" class="{% if request.resolver_match.url_name == 'project' %}active{% endif %}">Projects</a>
            </li>
            <li class="dropdown">
              <a href="javascript:void(0)" class="dropbtn">Expertise <i class="fas fa-chevron-down"></i></a>
              <div class="dropdown-boxes">
                <a href="{% url 'skill:skill' %}" class="dropdown-item">
                  <i class="fas fa-lightbulb"></i>
                  <div class="dropdown-text">
                    <div class="title">Skills</div>
                  </div>
                </a>
                <a href="{% url 'experience:experience' %}" class="dropdown-item">
                  <i class="fas fa-briefcase"></i>
                  <div class="dropdown-text">
                    <div class="title">Experience</div>
                  </div>
                </a>
                <a href="{% url 'edu:edu' %}" class="dropdown-item">
                  <i class="fas fa-graduation-cap"></i>
                  <div class="dropdown-text">
                    <div class="title">Education</div>
                  </div>
                </a>
              </div>
            </li>
            <li>
              <a href="{% url 'service:service' %}" class="{% if request.resolver_match.url_name == 'service' %}active{% endif %}">Services</a>
            </li>
            <li>
              <a href="{% url 'contact:contact' %}" class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">Contact</a>
            </li>
          </ul>
        </nav>
        <div class="hamburger">
          <i class="fas fa-bars"></i>
        </div>
      </div>
    </header>

    <main>
      {% block content %}
      {% endblock %}
    </main>

    <hr/>
    <footer class="footer-sub">
      <div class="footer-info">
        <p>
          © 2026 All Rights Reserved | Developed by
          <a href="https://www.facebook.com/Mominrifat09" target="_blank">Momin Ali Rifat</a>
        </p>
      </div>
    </footer>
    {% load static %}
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

portfolio/templates/contact/contact.html
{% extends "base.html" %} 
{% load static %}
{% block title %}
  Contact | Momin Rifat
{% endblock %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/cont.css' %}" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
{% endblock %}
{% block content %}
<div class="container">
    <h1 class="contact-title">Contact Me</h1>
    <div class="contact-form-section">
        <form id="contactForm">
            <div class="form-group">
                <label for="name"><i class="fa-solid fa-user"></i> Name</label>
                <input type="text" id="name" name="name" placeholder="Your Name" required>
            </div>
            <div class="form-group">
                <label for="email"><i class="fa-solid fa-envelope"></i> Email</label>
                <input type="email" id="email" name="email" placeholder="Your Mail" required>
            </div>
            <div class="form-group">
                <label for="subject"><i class="fa-solid fa-tag"></i> Subject</label>
                <input type="text" id="subject" name="subject" placeholder="Subject" required>
            </div>
            <div class="form-group">
                <label for="message"><i class="fa-solid fa-message"></i> Message</label>
                <textarea id="message" name="message" rows="5" placeholder="Your message..." required></textarea>
            </div>
            <button type="submit"><i class="fa-solid fa-paper-plane"></i> Send Message</button>
        </form>
    </div>
    <div class="contact-info-section">
        <div class="contact-logos">
            <a href="mailto:mominrifat8@gmail.com" target="_blank"><i class="fa-solid fa-envelope fa-2x"></i></a>
            <a href="https://linkedin.com/in/mominrifat" target="_blank"><i class="fa-brands fa-linkedin fa-2x"></i></a>
        </div>
        <div class="contact-details">
            <p><i class="fa-solid fa-phone"></i> +880 1811194021</p>
            <p><i class="fa-solid fa-location-dot"></i> 60/A Momin Hossen Lane, Narinda, Dhaka, Bangladesh</p>
        </div>
    </div>
</div>

<script>
const form = document.getElementById("contactForm");
form.addEventListener("submit", function(e) {
    e.preventDefault();
    const data = {
        name: form.name.value,
        email: form.email.value,
        subject: form.subject.value,
        message: form.message.value
    };
    fetch("https://script.google.com/macros/s/AKfycbyS8kI10Ah78OluhEr_AxXgfrZObyICg4FACiKsXrz5Y94oeQY5GRLhBIbrRQMsyCTQ/exec", {
        method: "POST",
        body: JSON.stringify(data)
    })
    .then(response => response.json())
    .then(data => {
        if(data.result === "success") {
            alert("Message sent!");
            form.reset();
        }
    })
    .catch(error => console.error("Error!", error.message));
});
</script>
{% endblock %}

portfolio/templates/edu/edu.html
{% extends "base.html" %} 
{% load static %}
{% block title %}
  Education | Momin Rifat
{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/edu.css' %}" />
{% endblock %}
{% block content %}
    <div class="container">
        <div class="section">
            <h2>Education</h2>
            <div class="card">
                <div class="title">University of Asia Pacific</div>
                <div class="subtitle">BSc. in Computer Science and Engineering</div>
                <div class="meta">CGPA: 3.97 / 4.00 | Jan 2024 -</div>
            </div>
            <div class="card">
                <div class="title">Dhaka College, Dhaka</div>
                <div class="subtitle">Science</div>
                <div class="meta">GPA: 5.00 / 5.00 | 2022</div>
            </div>
            <div class="card"> 
                <div class="title">Narinda Govt. High School</div>
                <div class="subtitle">Science</div>
                <div class="meta">GPA: 5.00 / 5.00 | 2020</div>
            </div>
        </div>
        <div class="section">
            <h2>Awards & Certificates</h2>
            <div class="card">
                <div class="award">VC’s Award</div>
                <div class="award-desc">Achieved an average GPA of 4.00 out of 4.00</div>
                <div class="semester">2nd Year, 2nd Semester</div>
            </div>
            <div class="card">
                <div class="award">VC’s Award</div>
                <div class="award-desc">Achieved an average GPA of 4.00 out of 4.00</div>
                <div class="semester">2nd Year, 1st Semester</div>
            </div>
            <div class="card">
                <div class="award">VC’s Award</div>
                <div class="award-desc">Achieved an average GPA of 4.00 out of 4.00</div>
                <div class="semester">1st Year, 2nd Semester</div>
            </div>
             <div class="card">
                <div class="award">Dean’s Award</div>
                <div class="award-desc">Achieved an average GPA of 3.85 out of 4.00</div>
                <div class="semester">1st Year, 1st Semester</div>
            </div>
        </div>
    </div>
{% endblock %}

portfolio/templates/experience/exp.html
{% extends "base.html" %} 
{% load static %}
{% block title %}
  Experiences | Momin Rifat
{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/exp.css' %}" />
{% endblock %}
{% block content %}
<div class="expertise">
    <h1 class="skill-title"> Explore My All Experiences </h1>
    <div class="section-title">Competitive Programming</div>
    <div class="cp-profiles">
        <div class="cp-card">
            <h3 class="c1">Codeforces</h3>
            <p>Rating: 1117 (Max Rating)</p>
            <a href="https://codeforces.com/profile/Momin_Rifat" target="_blank">View Profile</a>
        </div>
        <div class="cp-card">
            <h3 class="c2">CodeChef</h3>
            <p>Rating: 1198 (1★)</p>
            <a href="https://www.codechef.com/users/momin_rifat" target="_blank">View Profile</a>
        </div>
        <div class="cp-card">
            <h3 class="c3">Beecrowd</h3>
            <p>Problems Solved: 100+</p>
            <a href="https://judge.beecrowd.com/en/users/statistics/906580" target="_blank">View Profile</a>
        </div>
        <div class="streak-box">
            <img src="{% static 'images/cfst.png' %}" alt="Codeforces Streak">
            <p>Codeforces Streak</p>
        </div>
    </div>
    <div class="section-title">ICPC & Contest Participation</div>
    <div class="contest-list">
        <div class="contest-item">ICPC Dhaka Regional 2025</div>
        <div class="contest-item">ICPC Preliminary Contest 2025</div>
        <div class="contest-item">CUET Inter University Programming Contest (IUPC) 2025</div>
        <div class="contest-item">Intra Metropolitan University Programming Contest (IMUPC) 2025</div>
        <div class="contest-item">UAP Inter-University Collaborative Programming Contest 1.0</div>
        <div class="contest-item">BUBT Collaborative Programming Contest -1</div>
        <div class="contest-item last-item">BUBT Collaborative Programming Contest -2</div>
    </div>
    <div class="section-title">Academic & Club Activities</div>
    <div class="club-section">
        <div class="club-card">
            <h3>Programming Contest Club</h3>
            <p>Active Member</p>
        </div>
        <div class="club-card">
            <h3>Math Club</h3>
            <p>Active Member</p>
        </div>
    </div>
</div>
{% endblock %}

portfolio/templates/home/home.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
  Home | Momin Rifat
{% endblock %}
{% block extra_css %}
  <link rel="stylesheet" href="{% static 'css/home.css' %}" />
{% endblock %}
{% block content %}
  <div class="pic-about">
    <div class="pic">
      <img class="profile-pic" src="{% static 'images/rifat.jpeg' %}" alt="Profile Picture" />
      <hr />
      <h1 class="deg">Momin Ali Rifat</h1>
      <div class="social-links">
        <a href="https://www.facebook.com/Mominrifat09" target="_blank"><i class="fab fa-facebook-f"></i></a>
        <a href="https://github.com/MominRifat" target="_blank"><i class="fab fa-github"></i></a>
        <a href="https://www.linkedin.com/in/mominrifat/" target="_blank"><i class="fab fa-linkedin-in"></i></a>
        <a href="https://codeforces.com/profile/Momin_Rifat" target="_blank"><img src="{% static 'images/code.png' %}" alt="Codeforces" /></a>
      </div>
      <p class="designation">Creative Thinker | Programmer</p>
      <a href="{% static 'pdf/MominCV.pdf' %}" class="resume" target="_blank">View Resume</a>
    </div>

    <div class="about">
      <h2>About Me</h2>
      <p>I am a CSE student with a strong passion for Competitive Programming, Data Structures, and Algorithms. I have represented my university in ICPC and IUPC, honing my problem-solving and algorithmic skills. Beyond competitions, I actively work on software projects, exploring new technologies and building practical, real-world applications. I am always eager to learn, collaborate, and take on challenges that push my skills and creativity to the next level.</p>
      <div class="stats">
        <div class="stat">
          <div class="number">1000+</div>
          <div class="label">Problems Solved</div>
        </div>
        <div class="stat">
          <div class="number">10+</div>
          <div class="label">Projects</div>
        </div>
        <div class="stat">
          <div class="number">5+</div>
          <div class="label">IUPC</div>
        </div>
      </div>
    </div>
  </div>
  






  <div class="projects-section">
    <p class="project-tag">🚀</p>
    <h1 class="project-head">Projects</h1>
    <p class="project-para">Discover all exciting projects I have worked on</p>

    <div class="projects-grid">
      <div class="project-card">
        <img src="{% static 'images/website.jpeg' %}" alt="Math Club Website" />
        <p class="project-title">Math Club Website</p>
      </div>
      <div class="project-card">
        <img src="{% static 'images/ttt.png' %}" alt="Hotel Management System" />
        <p class="project-title">Tic Tac Toe</p>
      </div>
      <div class="project-card">
        <img src="{% static 'images/snake.png' %}" alt="Snake Game" />
        <p class="project-title">Snake Game</p>
      </div>
    </div>
    <div class="link-container">
      <a href="{% url 'project:project' %}" class="project-link {% if request.resolver_match.url_name == 'project' %}active{% endif %}">Explore All Projects</a>
    </div>
  </div>









  <div class="expatise-section">
      <p class="expatise-tag">⭐</p>
      <h1 class="expatise-head">Expertise</h1>
      <p class="expatise-para">Discover my Skill, Experience & Education</p>
      <div class="do-cards">

          <div class="terminal-card">
              <div class="terminal-header">
                  <span class="dot red"></span>
                  <span class="dot yellow"></span>
                  <span class="dot green"></span>
              </div>
              <pre>
  <span class="cpp-comment">// Skills</span>
  <span class="cpp-keyword">#include</span> &lt;iostream&gt;
  <span class="cpp-keyword">#include</span> &lt;vector&gt;
  <span class="cpp-keyword">using</span> <span class="cpp-keyword">namespace</span> std;

  <span class="cpp-type">int</span> <span class="cpp-function">main</span>() {
      <span class="cpp-type">vector</span>&lt;string&gt; <span class="vari">languages</span> = {
          <span class="cpp-string">"C"</span>, <span class="cpp-string">"C++"</span>, <span class="cpp-string">"Python"</span>, <span class="cpp-string">"SQL"</span>
          <span class="cpp-string">"Java"</span>, <span class="cpp-string">"JavaScript"</span>,
      };
      <span class="cpp-type">vector</span>&lt;string&gt; <span class="vari">skills</span> = {
          <span class="cpp-string">"Data Structures"</span>, <span class="cpp-string">"Algorithms"</span>,
          <span class="cpp-string">"Problem Solving"</span>
      };
      <span class="cpp-keyword">return</span> <span class="cpp-number">0</span>;
  }
              </pre>
          </div>

          <div class="terminal-card">
              <div class="terminal-header">
                  <span class="dot red"></span>
                  <span class="dot yellow"></span>
                  <span class="dot green"></span>
              </div>
              <pre>
  <span class="cpp-comment">// Experience</span>
  <span class="cpp-keyword">#include</span> &lt;iostream&gt;
  <span class="cpp-keyword">#include</span> &lt;vector&gt;
  <span class="cpp-keyword">using</span> <span class="cpp-keyword">namespace</span> std;

  <span class="cpp-type">int</span> <span class="cpp-function">main</span>() {
      <span class="cpp-type">int</span> <span class="vari">problemsSolved<span> = <span class="cpp-number">1000</span>;
      <span class="cpp-type">int</span> <span class="vari">projects</span> = <span class="cpp-number">10</span>;
      <span class="cpp-type">vector</span>&lt;string&gt;<span class="vari"> contests</span> = {
          <span class="cpp-string">"5+ IUPC"</span>,
          <span class="cpp-string">"1 ICPC"</span>
      };
      <span class="cpp-keyword">return</span> <span class="cpp-number">0</span>;
  }
              </pre>
          </div>

          <div class="terminal-card">
              <div class="terminal-header">
                  <span class="dot red"></span>
                  <span class="dot yellow"></span>
                  <span class="dot green"></span>
              </div>
              <pre>
  <span class="cpp-comment">// Education</span>
  <span class="cpp-keyword">#include</span> &lt;iostream&gt;
  <span class="cpp-keyword">using</span> <span class="cpp-keyword">namespace</span> std;

  <span class="cpp-type">int</span> <span class="cpp-function">main</span>() {
      <span class="cpp-type">vector</span>&lt;string&gt; <span class="vari">education</span> = {
          <span class="cpp-string">"University of Asia Pacific"</span>,
          <span class="cpp-string">"Department: CSE"</span>,
          <span class="cpp-string">"Current Semester: 3.1"</span>
      };
      <span class="cpp-keyword">return</span> <span class="cpp-number">0</span>;
  }
              </pre>
          </div>

      </div>

      <div class="link-container">
          <p>Explore Expertise</p>
      </div>
  </div>






  <div class="service-section">
    <p class="service-tag">⚡</p>
    <h1 class="service-head">Services</h1>
    <p class="service-para">Discover the services I offer to help you succeed</p>
    <div class="services-grid">
      <div class="service-card">
        <i class="fas fa-code service-icon"></i>
        <h3 class="service-title">Competitive Programming Guideline</h3>
      </div>
      <div class="service-card">
        <i class="fas fa-laptop-code service-icon"></i>
        <h3 class="service-title">Web Development Service</h3>
      </div>
    </div>
    <div class="link-container">
      <a href="{% url 'service:service' %}" class="services-link {% if request.resolver_match.url_name == 'service' %}active{% endif %}">Explore All Services</a>
    </div>
  </div>



{% endblock %}

portfolio/templates/service/service.html
{% extends "base.html" %} 
{% load static %}
{% block title %}
  Services | Momin Rifat
{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/serve.css' %}" />
{% endblock %}
{% block content %}
    <div class="service-container">
        <div class="service-status">
            <h1>No Services Available</h1>
            <p>Currently, no services are available. Please check back later.</p>
            <p>Thank you for your patience.</p>
        </div>
    </div>
{% endblock %}

portfolio/templates/skill/skill.html
{% extends "base.html" %} 
{% load static %}
{% block title %}
  Skills | Momin Rifat
{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/skill.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css">
{% endblock %}
{% block content %}
<div class="skill-container">
    <h1 class="skill-title"> Explore My All Skills </h1>

    <div class="skills-group">
        <h3>Programming Languages</h3>
        <div class="skills-grid">
            <div class="tech-item-1">
                <img src="{% static 'icons/c.png' %}" alt="C" class="tech-logo">
                <span>C</span>
            </div>
            <div class="tech-item-1">
                <img src="{% static 'icons/cpp.png' %}" alt="C++" class="tech-logo">
                <span>C++</span>
            </div>
            <div class="tech-item-1">
                <img src="{% static 'icons/java.png' %}" alt="Java" class="tech-logo">
                <span>Java</span>
            </div>
            <div class="tech-item-1">
                <img src="{% static 'icons/py.png' %}" alt="Python" class="tech-logo">
                <span>Python</span>
            </div>
            <div class="tech-item-1">
                <img src="{% static 'icons/sql.png' %}" alt="SQL" class="tech-logo">
                <span>SQL</span>
            </div>
        </div>
    </div>

    <div class="skills-group">
        <h3>Web Technologies</h3>
        <div class="skills-grid">
            <div class="tech-item">
                <img src="{% static 'icons/html5.png' %}" alt="HTML5" class="tech-logo">
                <span>HTML</span>
            </div>
            <div class="tech-item">
                <img src="{% static 'icons/css.png' %}" alt="CSS3" class="tech-logo">
                <span>CSS</span>
            </div>
            <div class="tech-item">
                <img src="{% static 'icons/js.png' %}" alt="JavaScript" class="tech-logo">
                <span>JavaScript</span>
            </div>
            <div class="tech-item">
                <img src="{% static 'icons/bt.png' %}" alt="Bootstrap" class="tech-logo">
                <span>Bootstrap</span>
            </div>
            <div class="tech-item">
                <img src="{% static 'icons/tl.png' %}" alt="Tailwind" class="tech-logo">
                <span>Tailwind</span>
            </div>
            <div class="tech-item">
                <img src="{% static 'icons/flask.png' %}" alt="Flask" class="tech-logo">
                <span>Flask</span>
            </div>
            <div class="tech-item">
                <img src="{% static 'icons/django.ico' %}" alt="Django" class="tech-logo">
                <span>Django</span>
            </div>
            <div class="tech-item">
                <img src="{% static 'icons/mysql.png' %}" alt="MySQL" class="tech-logo">
                <span>MySQL</span>
            </div>
        </div>
    </div>

    <div class="skills-group">
        <h3>Java Technologies</h3>
        <div class="skills-grid">
            <div class="tech-item">
                <img src="{% static 'icons/fx.png' %}" alt="JavaFX" class="tech-logo">
                <span>JavaFX</span>
            </div>
            <div class="tech-item">
                <img src="{% static 'icons/sc.png' %}" alt="Scene Builder" class="tech-logo">
                <span>Scene Builder</span>
            </div>
        </div>
    </div>

    <div class="skills-group">
        <h3>Tools & Platforms</h3>
        <div class="skills-grid">
            <div class="tech-item">
                <img src="{% static 'icons/git.png' %}" alt="Git" class="tech-logo">
                <span>Git</span>
            </div>
            <div class="tech-item">
                <img src="{% static 'icons/gh.png' %}" alt="GitHub" class="tech-logo">
                <span>GitHub</span>
            </div>
            <div class="tech-item">
                <img src="{% static 'icons/vs.png' %}" alt="VS Code" class="tech-logo">
                <span>VS Code</span>
            </div>
            <div class="tech-item">
                <img src="{% static 'icons/xm.png' %}" alt="XAMPP" class="tech-logo">
                <span>XAMPP</span>
            </div>
        </div>
    </div>
</div>
{% endblock %}